"""Compatibility exports for extracted reporting builders and review flows."""

from __future__ import annotations

from eco_council_runtime.application.investigation.review import (
    INVESTIGATION_LEG_METRIC_FAMILIES,
    build_hypothesis_review_from_state,
    build_investigation_review_draft_from_state,
    build_leg_review_from_state,
    investigation_leg_metric_families,
    investigation_review_overall_status,
    observation_supports_investigation_leg,
    record_has_investigation_tags,
    record_matches_hypothesis_leg,
    summarize_investigation_leg_status,
)
from eco_council_runtime.application.reporting.common import (
    claim_sort_key,
    claims_by_id_map,
    evidence_by_claim_map,
    evidence_rank,
    expected_output_kinds_for_role,
    gap_to_question,
    infer_missing_evidence_types,
    metrics_for_evidence,
    observations_by_id_map,
    report_has_substance,
    report_is_placeholder,
)
from eco_council_runtime.application.reporting.council_decision import (
    build_decision_draft_from_state,
    build_decision_missing_types,
    build_decision_summary_from_state,
    build_final_brief,
    completion_score_for_round,
    evidence_resolution_score,
    evidence_sufficiency_for_round,
    missing_types_from_reason_texts,
    readiness_score,
    report_completion_score,
)
from eco_council_runtime.application.reporting.expert_reports import (
    build_environmentalist_findings,
    build_expert_report_draft_from_state,
    build_open_questions,
    build_report_draft,
    build_report_summary_from_state,
    build_sociologist_findings,
    build_summary_for_role,
    expert_report_status_from_state,
    report_status_for_role,
)
from eco_council_runtime.application.reporting.readiness import (
    build_data_readiness_draft,
    build_pre_match_report_findings,
    build_readiness_findings_from_submissions,
    environment_role_required,
    generic_readiness_recommendations,
    observation_metrics_from_submissions,
    readiness_missing_types,
)

__all__ = [
    "INVESTIGATION_LEG_METRIC_FAMILIES",
    "build_data_readiness_draft",
    "build_decision_draft_from_state",
    "build_decision_missing_types",
    "build_decision_summary_from_state",
    "build_environmentalist_findings",
    "build_expert_report_draft_from_state",
    "build_final_brief",
    "build_hypothesis_review_from_state",
    "build_investigation_review_draft_from_state",
    "build_leg_review_from_state",
    "build_open_questions",
    "build_pre_match_report_findings",
    "build_readiness_findings_from_submissions",
    "build_report_draft",
    "build_report_summary_from_state",
    "build_sociologist_findings",
    "build_summary_for_role",
    "claim_sort_key",
    "claims_by_id_map",
    "completion_score_for_round",
    "evidence_by_claim_map",
    "evidence_rank",
    "evidence_resolution_score",
    "evidence_sufficiency_for_round",
    "environment_role_required",
    "expert_report_status_from_state",
    "expected_output_kinds_for_role",
    "gap_to_question",
    "generic_readiness_recommendations",
    "infer_missing_evidence_types",
    "investigation_leg_metric_families",
    "investigation_review_overall_status",
    "metrics_for_evidence",
    "missing_types_from_reason_texts",
    "observation_metrics_from_submissions",
    "observation_supports_investigation_leg",
    "observations_by_id_map",
    "readiness_missing_types",
    "readiness_score",
    "record_has_investigation_tags",
    "record_matches_hypothesis_leg",
    "report_completion_score",
    "report_has_substance",
    "report_is_placeholder",
    "report_status_for_role",
    "summarize_investigation_leg_status",
]
