from __future__ import annotations

from pathlib import Path
from typing import Callable

from .kernel.transition_requests import (
    TRANSITION_KIND_CLOSE_ROUND,
    TRANSITION_KIND_OPEN_INVESTIGATION_ROUND,
    TRANSITION_KIND_FREEZE_REPORT_BASIS,
)
from .runtime_command_hints import kernel_command, run_skill_command

HardGateCommandBuilder = Callable[..., dict[str, str]]
EntryChainBuilder = Callable[..., list[dict[str, str]]]


def default_phase2_hard_gate_commands(
    *,
    run_dir: Path,
    run_id: str,
    round_id: str,
    next_round_id: str,
    contract_mode: str,
) -> dict[str, str]:
    return {
        "show_run_state": kernel_command(
            "show-run-state",
            "--run-dir",
            str(run_dir),
            "--round-id",
            round_id,
            "--tail",
            "20",
            "--pretty",
        ),
        "supervise_round": kernel_command(
            "supervise-round",
            "--run-dir",
            str(run_dir),
            "--run-id",
            run_id,
            "--round-id",
            round_id,
            "--pretty",
        ),
        "apply_report_basis_gate": kernel_command(
            "apply-report-basis-gate",
            "--run-dir",
            str(run_dir),
            "--run-id",
            run_id,
            "--round-id",
            round_id,
            "--pretty",
        ),
        "close_round": kernel_command(
            "close-round",
            "--run-dir",
            str(run_dir),
            "--run-id",
            run_id,
            "--round-id",
            round_id,
            "--transition-request-id",
            "<approved_request_id>",
            "--pretty",
        ),
        "request_close_round": kernel_command(
            "request-phase-transition",
            "--run-dir",
            str(run_dir),
            "--run-id",
            run_id,
            "--round-id",
            round_id,
            "--transition-kind",
            TRANSITION_KIND_CLOSE_ROUND,
            "--rationale",
            "<rationale>",
            actor_role="moderator",
        ),
        "request_report_basis_transition": kernel_command(
            "request-phase-transition",
            "--run-dir",
            str(run_dir),
            "--run-id",
            run_id,
            "--round-id",
            round_id,
            "--transition-kind",
            TRANSITION_KIND_FREEZE_REPORT_BASIS,
            "--rationale",
            "<rationale>",
            actor_role="moderator",
        ),
        "open_next_round": run_skill_command(
            run_dir=run_dir,
            run_id=run_id,
            round_id=next_round_id,
            skill_name="open-investigation-round",
            actor_role="moderator",
            contract_mode=contract_mode,
            skill_args=[
                "--source-round-id",
                round_id,
                "--transition-request-id",
                "<approved_request_id>",
            ],
        ),
        "request_open_next_round": kernel_command(
            "request-phase-transition",
            "--run-dir",
            str(run_dir),
            "--run-id",
            run_id,
            "--round-id",
            round_id,
            "--transition-kind",
            TRANSITION_KIND_OPEN_INVESTIGATION_ROUND,
            "--target-round-id",
            next_round_id,
            "--source-round-id",
            round_id,
            "--rationale",
            "<rationale>",
            actor_role="moderator",
        ),
        "approve_transition_request": kernel_command(
            "approve-phase-transition",
            "--run-dir",
            str(run_dir),
            "--request-id",
            "<request_id>",
            "--approval-reason",
            "<approval_reason>",
        ),
        "reject_transition_request": kernel_command(
            "reject-phase-transition",
            "--run-dir",
            str(run_dir),
            "--request-id",
            "<request_id>",
            "--rejection-reason",
            "<rejection_reason>",
        ),
    }


def default_phase2_entry_chain(
    *,
    run_dir: Path,
    run_id: str,
    round_id: str,
    contract_mode: str,
    next_round_id: str,
) -> list[dict[str, str]]:
    return [
        {
            "step_id": "inspect-runtime",
            "mode": "runtime-gate",
            "objective": "Inspect governance, health, and current round posture before agent work begins.",
            "command": kernel_command(
                "show-run-state",
                "--run-dir",
                str(run_dir),
                "--round-id",
                round_id,
                "--tail",
                "20",
                "--pretty",
            ),
        },
        {
            "step_id": "read-board-delta",
            "mode": "advisory-read",
            "objective": "Read the current round directly from deliberation-plane state instead of depending on stale summaries.",
            "command": run_skill_command(
                run_dir=run_dir,
                run_id=run_id,
                round_id=round_id,
                skill_name="query-board-delta",
                actor_role="moderator",
                contract_mode=contract_mode,
                skill_args=["--include-closed", "--event-limit", "20"],
            ),
        },
        {
            "step_id": "query-shared-planes",
            "mode": "advisory-read",
            "objective": "Read normalized public/environment signals and current analysis result sets without leaving governed runtime surfaces.",
            "command": run_skill_command(
                run_dir=run_dir,
                run_id=run_id,
                round_id=round_id,
                skill_name="query-public-signals",
                actor_role="moderator",
                contract_mode=contract_mode,
            ),
        },
        {
            "step_id": "submit-council-proposal",
            "mode": "governed-write",
            "objective": "Push findings back as one structured council proposal in the deliberation DB instead of hiding judgement in freeform notes or in-memory state.",
            "command": run_skill_command(
                run_dir=run_dir,
                run_id=run_id,
                round_id=round_id,
                skill_name="submit-council-proposal",
                actor_role="moderator",
                contract_mode=contract_mode,
                skill_args=[
                    "--agent-role",
                    "moderator",
                    "--proposal-kind",
                    "<proposal_kind>",
                    "--rationale",
                    "<rationale>",
                    "--confidence",
                    "<confidence_0_to_1>",
                    "--target-kind",
                    "<target_kind>",
                    "--target-id",
                    "<target_id>",
                    "--evidence-ref",
                    "<evidence_ref>",
                    "--provenance-json",
                    "{\"source\":\"<provenance_source>\"}",
                ],
            ),
        },
        {
            "step_id": "submit-readiness-opinion",
            "mode": "governed-write",
            "objective": "When the council is making a readiness judgement, submit it as a DB-backed readiness opinion before returning to runtime gates.",
            "command": run_skill_command(
                run_dir=run_dir,
                run_id=run_id,
                round_id=round_id,
                skill_name="submit-readiness-opinion",
                actor_role="moderator",
                contract_mode=contract_mode,
                skill_args=[
                    "--agent-role",
                    "moderator",
                    "--readiness-status",
                    "<ready|needs-more-data|blocked>",
                    "--rationale",
                    "<rationale>",
                    "--basis-object-id",
                    "<basis_object_id>",
                ],
            ),
        },
        {
            "step_id": "request-report-basis-transition",
            "mode": "runtime-gate",
            "objective": "When the moderator considers the round promotable, file an explicit report-basis transition request before operator review.",
            "command": kernel_command(
                "request-phase-transition",
                "--run-dir",
                str(run_dir),
                "--run-id",
                run_id,
                "--round-id",
                round_id,
                "--transition-kind",
                TRANSITION_KIND_FREEZE_REPORT_BASIS,
                "--rationale",
                "<rationale>",
                actor_role="moderator",
            ),
        },
        {
            "step_id": "approve-transition-request",
            "mode": "runtime-gate",
            "objective": "Runtime operator approves or rejects the moderator transition request before the controller can execute any committed state change.",
            "command": kernel_command(
                "approve-phase-transition",
                "--run-dir",
                str(run_dir),
                "--request-id",
                "<request_id>",
                "--approval-reason",
                "<approval_reason>",
            ),
        },
        {
            "step_id": "return-to-runtime-gate",
            "mode": "runtime-gate",
            "objective": "Hand the updated round back to the runtime supervisor so it can execute only already-approved transition work.",
            "command": kernel_command(
                "supervise-round",
                "--run-dir",
                str(run_dir),
                "--run-id",
                run_id,
                "--round-id",
                round_id,
                "--pretty",
            ),
        },
        {
            "step_id": "open-follow-up-round",
            "mode": "governed-write",
            "objective": "If the round remains open, the moderator must file an explicit next-round transition request before operator approval and follow-up round creation.",
            "command": kernel_command(
                "request-phase-transition",
                "--run-dir",
                str(run_dir),
                "--run-id",
                run_id,
                "--round-id",
                round_id,
                "--transition-kind",
                TRANSITION_KIND_OPEN_INVESTIGATION_ROUND,
                "--target-round-id",
                next_round_id,
                "--source-round-id",
                round_id,
                "--rationale",
                "<rationale>",
                actor_role="moderator",
            ),
        },
    ]
