"""Compatibility exports for reporting artifact packet, prompt, and promotion flows."""

from __future__ import annotations

from eco_council_runtime.application.reporting.artifact_pipeline import (
    curation_artifacts,
    curation_status_complete,
    curations_materialized_for_round,
    data_readiness_artifacts,
    decision_artifacts,
    investigation_review_artifacts,
    matching_adjudication_artifacts,
    matching_authorization_artifacts,
    report_artifacts,
)
from eco_council_runtime.application.reporting.artifact_support import (
    PROMOTABLE_REPORT_ROLES,
    READINESS_ROLES,
    REPORT_ROLES,
    load_report_for_decision,
    write_text,
)
from eco_council_runtime.application.reporting.packets import (
    SCHEMA_VERSION,
    build_claim_curation_draft,
    build_claim_curation_instructions,
    build_claim_curation_packet,
    build_data_readiness_instructions,
    build_data_readiness_packet,
    build_decision_packet_from_state,
    build_investigation_review_instructions,
    build_investigation_review_packet,
    build_matching_adjudication_instructions,
    build_matching_adjudication_packet,
    build_matching_authorization_draft,
    build_matching_authorization_instructions,
    build_matching_authorization_packet,
    build_observation_curation_draft,
    build_observation_curation_instructions,
    build_observation_curation_packet,
    build_report_instructions,
    build_report_packet,
)
from eco_council_runtime.application.reporting.prompts import (
    claim_curation_prompt_text,
    data_readiness_prompt_text,
    investigation_review_prompt_text,
    matching_adjudication_prompt_text,
    matching_authorization_prompt_text,
    observation_curation_prompt_text,
    render_openclaw_prompts,
)
from eco_council_runtime.application.reporting.promotion import (
    load_decision_draft_payload,
    load_investigation_review_draft_payload,
    load_matching_adjudication_draft_payload,
    load_matching_authorization_draft_payload,
    load_report_draft_payload,
    promote_decision_draft,
    promote_investigation_review_draft,
    promote_matching_adjudication_draft,
    promote_matching_authorization_draft,
    promote_report_draft,
)

__all__ = [
    "PROMOTABLE_REPORT_ROLES",
    "READINESS_ROLES",
    "REPORT_ROLES",
    "SCHEMA_VERSION",
    "build_claim_curation_draft",
    "build_claim_curation_instructions",
    "build_claim_curation_packet",
    "build_data_readiness_instructions",
    "build_data_readiness_packet",
    "build_decision_packet_from_state",
    "build_investigation_review_instructions",
    "build_investigation_review_packet",
    "build_matching_adjudication_instructions",
    "build_matching_adjudication_packet",
    "build_matching_authorization_draft",
    "build_matching_authorization_instructions",
    "build_matching_authorization_packet",
    "build_observation_curation_draft",
    "build_observation_curation_instructions",
    "build_observation_curation_packet",
    "build_report_instructions",
    "build_report_packet",
    "claim_curation_prompt_text",
    "curation_artifacts",
    "curation_status_complete",
    "curations_materialized_for_round",
    "data_readiness_artifacts",
    "data_readiness_prompt_text",
    "decision_artifacts",
    "investigation_review_artifacts",
    "investigation_review_prompt_text",
    "load_decision_draft_payload",
    "load_investigation_review_draft_payload",
    "load_matching_adjudication_draft_payload",
    "load_matching_authorization_draft_payload",
    "load_report_draft_payload",
    "load_report_for_decision",
    "matching_adjudication_artifacts",
    "matching_adjudication_prompt_text",
    "matching_authorization_artifacts",
    "matching_authorization_prompt_text",
    "observation_curation_prompt_text",
    "promote_decision_draft",
    "promote_investigation_review_draft",
    "promote_matching_adjudication_draft",
    "promote_matching_authorization_draft",
    "promote_report_draft",
    "render_openclaw_prompts",
    "report_artifacts",
    "write_text",
]
