from __future__ import annotations

from .types import CanonicalContract, PLANE_DELIBERATION, _contract


DELIBERATION_CONTRACTS: dict[str, CanonicalContract] = {
    "proposal": _contract(
        "proposal",
        plane=PLANE_DELIBERATION,
        schema_version="council-proposal-v1",
        id_field="proposal_id",
        required_text_fields=(
            "decision_source",
            "proposal_kind",
            "agent_role",
            "status",
            "target_kind",
            "target_id",
            "rationale",
        ),
        required_list_fields=("evidence_refs", "lineage", "response_to_ids"),
        required_dict_fields=("provenance", "target"),
        required_number_fields=("confidence",),
        required_non_empty_list_fields=("evidence_refs",),
        required_non_empty_dict_fields=("provenance", "target"),
    ),
    "finding": _contract(
        "finding",
        plane=PLANE_DELIBERATION,
        schema_version="finding-record-v1",
        id_field="finding_id",
        required_text_fields=(
            "decision_source",
            "finding_kind",
            "agent_role",
            "status",
            "title",
            "summary",
            "rationale",
            "target_kind",
            "target_id",
        ),
        required_list_fields=(
            "evidence_refs",
            "lineage",
            "basis_object_ids",
            "source_signal_ids",
            "linked_bundle_ids",
            "response_to_ids",
        ),
        required_dict_fields=("provenance", "target"),
        required_number_fields=("confidence",),
        required_non_empty_list_fields=("evidence_refs",),
        required_non_empty_dict_fields=("provenance", "target"),
    ),
    "discussion-message": _contract(
        "discussion-message",
        plane=PLANE_DELIBERATION,
        schema_version="discussion-message-v1",
        id_field="message_id",
        required_text_fields=(
            "decision_source",
            "author_role",
            "message_kind",
            "status",
            "thread_id",
            "message_text",
            "target_kind",
            "target_id",
        ),
        required_list_fields=(
            "evidence_refs",
            "lineage",
            "response_to_ids",
            "related_object_ids",
        ),
        required_dict_fields=("provenance", "target"),
        required_non_empty_dict_fields=("provenance", "target"),
    ),
    "evidence-bundle": _contract(
        "evidence-bundle",
        plane=PLANE_DELIBERATION,
        schema_version="evidence-bundle-v1",
        id_field="bundle_id",
        required_text_fields=(
            "decision_source",
            "bundle_kind",
            "agent_role",
            "status",
            "title",
            "summary",
            "rationale",
            "target_kind",
            "target_id",
        ),
        required_list_fields=(
            "evidence_refs",
            "lineage",
            "basis_object_ids",
            "source_signal_ids",
            "finding_ids",
        ),
        required_dict_fields=("provenance", "target"),
        required_number_fields=("confidence",),
        required_non_empty_list_fields=("evidence_refs",),
        required_non_empty_dict_fields=("provenance", "target"),
    ),
    "review-comment": _contract(
        "review-comment",
        plane=PLANE_DELIBERATION,
        schema_version="review-comment-v1",
        id_field="comment_id",
        required_text_fields=(
            "decision_source",
            "author_role",
            "review_kind",
            "status",
            "thread_id",
            "comment_text",
            "target_kind",
            "target_id",
        ),
        required_list_fields=("evidence_refs", "lineage", "response_to_ids"),
        required_dict_fields=("provenance", "target"),
        required_non_empty_dict_fields=("provenance", "target"),
        optional_text_fields=("report_risk", "constraint_disposition"),
        optional_list_fields=("required_followup_evidence",),
    ),
    "hypothesis": _contract(
        "hypothesis",
        plane=PLANE_DELIBERATION,
        schema_version="hypothesis-card-v1",
        id_field="hypothesis_id",
        required_text_fields=("decision_source", "status", "title", "owner_role"),
        required_list_fields=(
            "evidence_refs",
            "lineage",
            "linked_claim_ids",
            "source_ids",
        ),
    ),
    "challenge": _contract(
        "challenge",
        plane=PLANE_DELIBERATION,
        schema_version="challenge-ticket-v1",
        id_field="ticket_id",
        required_text_fields=(
            "decision_source",
            "status",
            "title",
            "challenge_statement",
            "owner_role",
        ),
        required_list_fields=(
            "evidence_refs",
            "lineage",
            "source_ids",
            "linked_artifact_refs",
            "related_task_ids",
        ),
    ),
    "board-task": _contract(
        "board-task",
        plane=PLANE_DELIBERATION,
        schema_version="board-task-v1",
        id_field="task_id",
        required_text_fields=("decision_source", "status", "title", "owner_role"),
        required_list_fields=(
            "evidence_refs",
            "lineage",
            "source_ids",
            "linked_artifact_refs",
            "related_ids",
        ),
    ),
    "next-action": _contract(
        "next-action",
        plane=PLANE_DELIBERATION,
        schema_version="next-action-v1",
        id_field="action_id",
        required_text_fields=(
            "decision_source",
            "action_kind",
            "assigned_role",
            "objective",
            "reason",
            "target_object_kind",
            "target_object_id",
        ),
        required_list_fields=("evidence_refs", "lineage", "source_ids"),
        required_dict_fields=("provenance", "target"),
    ),
    "probe": _contract(
        "probe",
        plane=PLANE_DELIBERATION,
        schema_version="probe-v1",
        id_field="probe_id",
        required_text_fields=(
            "decision_source",
            "probe_status",
            "probe_type",
            "owner_role",
            "probe_goal",
            "falsification_question",
            "target_object_kind",
            "target_object_id",
        ),
        required_list_fields=(
            "evidence_refs",
            "lineage",
            "source_ids",
            "requested_skills",
            "success_criteria",
            "disconfirm_signals",
        ),
        required_dict_fields=("provenance", "target"),
    ),
    "readiness-opinion": _contract(
        "readiness-opinion",
        plane=PLANE_DELIBERATION,
        schema_version="readiness-opinion-v1",
        id_field="opinion_id",
        required_text_fields=(
            "decision_source",
            "agent_role",
            "opinion_status",
            "readiness_status",
            "rationale",
        ),
        required_list_fields=("evidence_refs", "lineage", "basis_object_ids"),
    ),
    "readiness-assessment": _contract(
        "readiness-assessment",
        plane=PLANE_DELIBERATION,
        schema_version="readiness-assessment-v1",
        id_field="readiness_id",
        required_text_fields=("decision_source", "readiness_status"),
        optional_list_fields=(
            "basis_object_ids",
            "selected_basis_object_ids",
            "selected_evidence_refs",
            "opinion_ids",
            "challenger_constraint_ids",
            "unresolved_challenger_constraint_ids",
            "challenger_constraints",
            "unresolved_challenger_constraints",
            "basis_use_constraints",
        ),
        optional_number_fields=(
            "challenger_constraint_count",
            "unresolved_challenger_constraint_count",
        ),
    ),
    "report-basis-freeze": _contract(
        "report-basis-freeze",
        plane=PLANE_DELIBERATION,
        schema_version="report-basis-freeze-v1",
        id_field="basis_id",
        required_text_fields=("decision_source", "report_basis_status", "readiness_status"),
        optional_list_fields=(
            "basis_object_ids",
            "selected_basis_object_ids",
            "selected_evidence_refs",
            "candidate_bundle_evidence_refs",
            "unselected_candidate_bundle_evidence_refs",
            "challenger_constraint_ids",
            "unresolved_challenger_constraint_ids",
            "challenger_constraints",
            "unresolved_challenger_constraints",
            "basis_use_constraints",
            "explicit_report_claim_objects",
            "report_claim_structural_violations",
            "explicit_lead_basis_objects",
            "lead_basis_constraint_violations",
        ),
        optional_dict_fields=("report_claim_structure",),
        optional_number_fields=(
            "challenger_constraint_count",
            "unresolved_challenger_constraint_count",
            "explicit_report_claim_count",
            "report_claim_structural_violation_count",
            "explicit_lead_basis_count",
            "lead_basis_constraint_violation_count",
        ),
    ),
    "decision-trace": _contract(
        "decision-trace",
        plane=PLANE_DELIBERATION,
        schema_version="decision-trace-v1",
        id_field="trace_id",
        required_text_fields=("decision_source", "decision_id", "decision_kind", "status", "rationale"),
        required_list_fields=(
            "evidence_refs",
            "lineage",
            "accepted_object_ids",
            "rejected_object_ids",
        ),
    ),
}



__all__ = (
    "DELIBERATION_CONTRACTS",
)
